[build]
builder = "NIXPACKS"
buildCommand = "npm install && node seed.js"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[services]]
name = "neon-build"
